import { Question } from "./src/Constantes";

export const rounds = [
  {
    id: 1,
    name: "Personnalité",
  },
  {
    id: 2,
    name: "Situations",
  },
  {
    id: 3,
    name: "Relations",
  },
  {
    id: 4,
    name: "Représentations",
  },
];
export const questions: Question[] = [
  {
    id: 1,
    round_id: 1,
    name: "tes vrais amis, tu les comptes ...",
    answer_1: "Sur les doigts d'une main",
    answer_2: "Sur les deux mains",
    answer_3: "Tu n'as pas assez de doigts pour les compter",
    answer_4: "Tu n'en as pas",
  },
  {
    id: 2,
    round_id: 1,
    name: "à quelle fréquence tu t'observes à travers un miroir ou des photos ?",
    answer_1: "Plus souvent que la plupart des gens",
    answer_2: "Moins souvent que la plupart des gens",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 3,
    round_id: 1,
    name: "mens-tu ?",
    answer_1: "Plus que la plupart des gens",
    answer_2: "Moins que la plupart des gens",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 4,
    round_id: 1,
    name: "la vie à deux, pour toi c'est ...",
    answer_1: "Réconfortant",
    answer_2: "Excitant",
    answer_3: "Angoissant",
    answer_4: null,
  },
  {
    id: 5,
    round_id: 1,
    name: "on t'offre un cadeau qui ne te plaît pas, tu dis ...",
    answer_1: "Merci, ça me plaît beaucoup",
    answer_2: "Qu’est-ce que j’ai fait pour mériter ça ?",
    answer_3:
      "J’apprécie le geste mais ce n’est pas exactement ce dont j’ai l’utilité, peut-on l'échanger ?",
    answer_4: null,
  },
  {
    id: 6,
    round_id: 1,
    name: "tu ne supportes pas les gens ...",
    answer_1: "Vulgaires",
    answer_2: "Prétentieux",
    answer_3: "Fourbes",
    answer_4: null,
  },
  {
    id: 7,
    round_id: 1,
    name: "selon toi, le vol ...",
    answer_1: "N’est jamais justifiable",
    answer_2: "Peut-être justifié si nécessaire",
    answer_3: "Est un risque à partir du moment où l’on possède un bien",
    answer_4: null,
  },
  {
    id: 8,
    round_id: 1,
    name: "en cas de conflit, es-tu plus enclin à ...",
    answer_1: "L’éviter",
    answer_2: "Rechercher un compromis",
    answer_3: "Prendre position et défendre ton point de vue",
    answer_4: null,
  },
  {
    id: 9,
    round_id: 1,
    name: "lorsque tu fais face à un problème, dans un premier temps tu es plutôt enclin à ...",
    answer_1: "Rechercher des solutions par toi-même",
    answer_2: "Demander de l'aide",
    answer_3: "Éviter le problème et remettre à plus tard",
    answer_4: null,
  },
  {
    id: 10,
    round_id: 1,
    name: "pour toi, la moins mauvaise société serait ...",
    answer_1: "Technocratique",
    answer_2: "Socialiste",
    answer_3: "Libérale",
    answer_4: null,
  },
  {
    id: 11,
    round_id: 1,
    name: "selon toi, la tolérance ...",
    answer_1: "Est un naïf aveu de faiblesse",
    answer_2: "Doit être accordée à tous",
    answer_3: "Ne doit être accordée que lorsque cela te semble juste",
    answer_4: null,
  },
  {
    id: 12,
    round_id: 1,
    name: "pour toi, les inégalités sont ...",
    answer_1: "Insupportables",
    answer_2: "Inévitables",
    answer_3: "Souhaitables",
    answer_4: null,
  },
  {
    id: 13,
    round_id: 1,
    name: "pour toi, la vérité est ...",
    answer_1: "Un poids",
    answer_2: "Un droit",
    answer_3: "Une affaire d'interprétation",
    answer_4: null,
  },
  {
    id: 14,
    round_id: 1,
    name: "en politique, les sujets qui t'intéressent sont plutôt ...",
    answer_1: "Économiques",
    answer_2: "Sociaux",
    answer_3: "Environnementaux",
    answer_4: null,
  },
  {
    id: 15,
    round_id: 1,
    name: "tu préfères/préférerais que ton enfant soit  ...",
    answer_1: "Gentil",
    answer_2: "Intelligent",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 16,
    round_id: 1,
    name: "estimes-tu qu’il faille plus de courage pour  ...",
    answer_1: "Surmonter un traumatisme",
    answer_2: "Se donner la mort",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 17,
    round_id: 1,
    name: "quelle qualité t'attire le plus chez un partenaire romantique ...",
    answer_1: "Le physique",
    answer_2: "L'intelligence",
    answer_3: "L'humour",
    answer_4: null,
  },
  {
    id: 18,
    round_id: 1,
    name: "pour toi, le sexe c'est ...",
    answer_1: "Le ciment du couple",
    answer_2: "Un besoin physiologique",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 19,
    round_id: 1,
    name: "tu vis ta vie ...",
    answer_1: "Pour toi-même",
    answer_2: "Pour un idéal",
    answer_3: "Pour quelqu’un d’autre/pour d’autres",
    answer_4: null,
  },
  {
    id: 20,
    round_id: 1,
    name: "pour toi la richesse matérielle c’est ...",
    answer_1: "Un péché",
    answer_2: "Une chance",
    answer_3: "Une récompense",
    answer_4: null,
  },
  {
    id: 21,
    round_id: 1,
    name: "tu considères que la liberté d’expression doit être ...",
    answer_1: "Illimitée",
    answer_2: "Restreinte dans des espaces dédiés",
    answer_3: "Restreinte dans le contenu",
    answer_4: null,
  },
  {
    id: 22,
    round_id: 1,
    name: "pour toi la religion est ...",
    answer_1: "Une opportunité de donner un sens à ta vie",
    answer_2: "L’ancêtre de la politique",
    answer_3: "Dépassée à notre époque",
    answer_4: null,
  },
  {
    id: 23,
    round_id: 1,
    name: "pour toi, l’immigration ...",
    answer_1: "Doit être régulée",
    answer_2: "Doit être encouragée",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 24,
    round_id: 1,
    name: "pour toi, le réchauffement climatique ...",
    answer_1: "Est un problème urgent et primordial",
    answer_2: "Est un combat perdu d’avance",
    answer_3: "N’est pas une priorité",
    answer_4: null,
  },
  {
    id: 25,
    round_id: 1,
    name: "les conflits au Moyen-Orient ...",
    answer_1: "Te dépassent",
    answer_2: "T'indignent",
    answer_3: "Ne te concernent pas",
    answer_4: null,
  },
  {
    id: 26,
    round_id: 1,
    name: "la principale qualité que tu attends d'un ami, c'est ...",
    answer_1: "La disponibilité",
    answer_2: "La franchise",
    answer_3: "La complicité",
    answer_4: null,
  },
  {
    id: 27,
    round_id: 1,
    name: "pour toi, la soirée idéale serait plutôt ...",
    answer_1: "Au chaud à la maison",
    answer_2: "Un dîner en tête à tête",
    answer_3: "Une grande fête avec toutes tes relations",
    answer_4: null,
  },
  {
    id: 28,
    round_id: 1,
    name: "parler est pour toi ...",
    answer_1: "Un plaisir",
    answer_2: "Un effort",
    answer_3: "Un vice",
    answer_4: null,
  },
  {
    id: 29,
    round_id: 1,
    name: "si tu pouvais maîtriser un élément, lequel choisirais-tu ?",
    answer_1: "L’eau",
    answer_2: "La terre",
    answer_3: "Le feu",
    answer_4: "L’air",
  },
  {
    id: 30,
    round_id: 1,
    name: "si tu étais un objet, ce serait ...",
    answer_1: "Une lame",
    answer_2: "Une horloge",
    answer_3: "Un coussin",
    answer_4: null,
  },
  {
    id: 31,
    round_id: 1,
    name: "quelle qualité privilégies-tu chez un collègue de travail ?",
    answer_1: "Les compétences techniques",
    answer_2: "La compréhension globale",
    answer_3: "La bonne entente",
    answer_4: null,
  },
  {
    id: 32,
    round_id: 1,
    name: "en vacances, tu préfères ...",
    answer_1: "La plage",
    answer_2: "La montagne",
    answer_3: "Une grande ville",
    answer_4: null,
  },
  {
    id: 33,
    round_id: 1,
    name: "si tu avais une journée de congé, tu la passerais ...",
    answer_1: "À voir tes amis",
    answer_2: "À pratiquer un hobby",
    answer_3: "À faire du shopping",
    answer_4: null,
  },
  {
    id: 34,
    round_id: 1,
    name: "lors d'une discussion, es-tu plus enclin à ...",
    answer_1: "Écouter",
    answer_2: "Argumenter et débattre",
    answer_3: "Aller dans le sens de la discussion",
    answer_4: null,
  },
  {
    id: 35,
    round_id: 1,
    name: "pour toi, le progrès, c’est ...",
    answer_1: "Augmenter le niveau de confort",
    answer_2: "Pouvoir faire de nouvelles choses",
    answer_3: "Faire moins d’erreurs, être plus efficace",
    answer_4: null,
  },
  {
    id: 36,
    round_id: 1,
    name: "quelle est ta saison préférée ?",
    answer_1: "Printemps",
    answer_2: "Été",
    answer_3: "Automne",
    answer_4: "Hiver",
  },
  {
    id: 37,
    round_id: 1,
    name: "lorsque tu lis un livre, préfères-tu ...",
    answer_1: "Te plonger dans un récit",
    answer_2: "Te cultiver",
    answer_3: "Tu ne lis pas de livre",
    answer_4: null,
  },
  {
    id: 38,
    round_id: 1,
    name: "si tu étais un animal, tu serais ...",
    answer_1: "Carnivore",
    answer_2: "Herbivore",
    answer_3: "Omnivore",
    answer_4: null,
  },
  {
    id: 39,
    round_id: 1,
    name: "à propos des réseaux sociaux, tu ...",
    answer_1: "Les adores",
    answer_2: "Les utilises pour rester en contact",
    answer_3: "Vis sans",
    answer_4: null,
  },
  {
    id: 40,
    round_id: 1,
    name: "en tant que chef d'entreprise, tu valoriserais davantage ...",
    answer_1: "L’activité",
    answer_2: "La rentabilité",
    answer_3: "L’ambiance de travail",
    answer_4: null,
  },
  {
    id: 41,
    round_id: 1,
    name: "si tu pouvais observer (sans interaction) une période et un endroit donné dans le temps, irais-tu ...",
    answer_1: "Dans le passé",
    answer_2: "Dans le futur",
    answer_3: "Quelque part dans le présent",
    answer_4: null,
  },
  {
    id: 42,
    round_id: 1,
    name: "tu préfères les activités sportives ...",
    answer_1: "En équipe",
    answer_2: "En solo",
    answer_3: "Pas d'activité sportive",
    answer_4: null,
  },
  {
    id: 43,
    round_id: 1,
    name: "en cas de stress, es-tu plus enclin à ...",
    answer_1: "Te défouler",
    answer_2: "Te distraire",
    answer_3: "Te confier",
    answer_4: null,
  },
  {
    id: 44,
    round_id: 1,
    name: "tu estimes la valeur d’une personne à travers ...",
    answer_1: "Ses capacités",
    answer_2: "Ses accomplissements",
    answer_3: "Son comportement",
    answer_4: null,
  },
  {
    id: 45,
    round_id: 1,
    name: "quelle qualité t'attire le plus chez un mentor ...",
    answer_1: "La patience",
    answer_2: "La bienveillance",
    answer_3: "La compétence",
    answer_4: null,
  },
  {
    id: 46,
    round_id: 1,
    name: "face à une décision importante, es-tu plus enclin à ...",
    answer_1: "Suivre ton intuition",
    answer_2: "Analyser les faits et rationaliser",
    answer_3: "Consulter les conseils de tes proches",
    answer_4: null,
  },
  {
    id: 47,
    round_id: 1,
    name: "lors d'une soirée entre amis, es-tu plutôt ...",
    answer_1: "L’animateur",
    answer_2: "Le comique",
    answer_3: "Le discret",
    answer_4: null,
  },
  {
    id: 48,
    round_id: 1,
    name: "si tu étais un aliment, lequel serais-tu ? ...",
    answer_1: "Un bon burger bien gras",
    answer_2: "Un brocoli à la vapeur",
    answer_3: "Un risotto au poulet",
    answer_4: null,
  },
  {
    id: 49,
    round_id: 1,
    name: "tu es plutôt ...",
    answer_1: "Nihiliste",
    answer_2: "Existentialiste",
    answer_3: "Humaniste",
    answer_4: "Religieux",
  },
  {
    id: 50,
    round_id: 1,
    name: "tu as parfois l'impression de manquer ...",
    answer_1: "D'humilité",
    answer_2: "De culture",
    answer_3: "D'initiative",
    answer_4: null,
  },
  {
    id: 51,
    round_id: 2,
    name: "tu as une opportunité de carrière exceptionnelle à l'étranger, mais cela signifierait laisser derrière toi ta famille et tes amis proches pour une période non négligeable. Que choisis-tu ?",
    answer_1: "Je pars",
    answer_2: "Je reste",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 52,
    round_id: 2,
    name: "ton ami(e) a une altercation avec des inconnus. Prends-tu instinctivement son parti sachant qu’il/elle peut être en tort ?",
    answer_1: "Je prends son parti",
    answer_2: "Je reste en retrait",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 53,
    round_id: 2,
    name: "tu découvres qu'un ami très cher t'a caché un événement important de sa vie. Restes-tu son ami ?",
    answer_1: "Je reste son ami",
    answer_2: "Je m'en éloigne",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 54,
    round_id: 2,
    name: "tu as promis à quelqu'un de garder un secret. Gardes-tu le silence au risque de nuire à une autre personne ?",
    answer_1: "Je garde le silence",
    answer_2: "Je dévoile le secret",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 55,
    round_id: 2,
    name: "tu as des informations compromettantes sur un collègue de travail agaçant. Un supérieur hiérarchique te demande de les partager pour discréditer cette personne. Que fais-tu ?",
    answer_1: "Je partage les informations",
    answer_2: "Je garde le silence",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 56,
    round_id: 2,
    name: "tu es en désaccord avec un membre de ta famille sur une question politique très sensible. Défends-tu ton point de vue au risque de te mettre cette personne à dos ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 57,
    round_id: 2,
    name: "un ami te demande de le couvrir en mentant à sa moitié au sujet de sa présence à un événement. Acceptes-tu de mentir pour lui ou refuses-tu de participer à la duperie ?",
    answer_1: "J'accepte",
    answer_2: "Je refuse",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 58,
    round_id: 2,
    name: "un membre de ta famille fait des commentaires désobligeants sur ton partenaire. Confrontes-tu cette personne ou ignores-tu les commentaires pour éviter les conflits ?",
    answer_1: "Je la confronte",
    answer_2: "Je laisse couler",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 59,
    round_id: 2,
    name: "ton ami heureux en ménage est sur le point de commettre un adultère. Le dissuades-tu ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 60,
    round_id: 2,
    name: "ton partenaire tient un journal intime. Ce journal est laissé sans surveillance, le consultes-tu sans son consentement ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 61,
    round_id: 2,
    name: "tu organises une fête et un invité boit trop, devenant gênant pour les autres. Irais-tu jusqu’à le calmer devant tout le monde ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 62,
    round_id: 2,
    name: "tu n’arrives plus à faire l’amour et n’éprouves plus aucun désir. Autorises-tu ton partenaire à assouvir ses besoins sexuels avec d’autres personnes ? (Il/Elle n’est pas la cause de ton absence de libido)",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 63,
    round_id: 2,
    name: "un membre de ta famille te critique sévèrement sur ton mode de vie lors d’un repas. Lui réponds-tu ou gardes-tu ton calme pour ne pas envenimer les choses ?",
    answer_1: "Je me défends",
    answer_2: "Je laisse couler",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 64,
    round_id: 2,
    name: "tu as eu des relations sexuelles avec un(e) ami(e), t’éloignes-tu de cette personne une fois en couple ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 65,
    round_id: 2,
    name: "tu as un ami qui ne cesse de se plaindre de ses problèmes, mais ne semble jamais prendre de mesures pour les résoudre. Lui avoues-tu le fond de ta pensée ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 66,
    round_id: 2,
    name: "tu gagnes une grosse somme d’argent au casino quand tes amis ont perdu à la même soirée. Rembourses-tu leur perte si ton gain le permet ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 67,
    round_id: 2,
    name: "mettrais-tu un terme à une relation si toi et ton partenaire n’étiez pas d’accord sur l’idée d’avoir des enfants ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 68,
    round_id: 2,
    name: "tu constates qu’un proche s’éloigne peu à peu de toi. Tentes-tu de renouer avec la personne ou t’émancipes-tu de la relation ?",
    answer_1: "J'essaye de rattraper la personne",
    answer_2: "Je m'en éloigne",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 69,
    round_id: 2,
    name: "ton enfant se fait violer. Laisses-tu la justice s’en charger ou fais-tu justice toi-même ?",
    answer_1: "Je laisse la justice se charger de punir le coupable",
    answer_2: "Je me fais justice moi-même",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 70,
    round_id: 2,
    name: "tu apprends que ton ami(e) subit des violences conjugales. Agis-tu même si cet(te) ami(e) te demande de rester en dehors de ça ?",
    answer_1: "Je respecte son choix",
    answer_2: "J'interviens pour essayer de stopper les violences",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 71,
    round_id: 2,
    name: "partirais-tu d’Omelas ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 72,
    round_id: 2,
    name: "tu es condamné pour un crime. Dénonces-tu tes associés contre une remise de peine significative ?",
    answer_1: "Je balance",
    answer_2: "Je garde le silence",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 73,
    round_id: 2,
    name: "un ami te prête un objet et tu le casses accidentellement. Cependant ton ami ne se souvient pas de l’état de l’objet et pourrait croire que le défaut était déjà là avant de te le prêter. Avoues-tu ta maladresse ou fais-tu mine de rien ?",
    answer_1: "J'avoue",
    answer_2: "Je fais mine de rien",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 74,
    round_id: 2,
    name: "ton/ta meilleur(e) ami(e) est heureux en couple avec une personne que tu méprises. Partages-tu ta perspective ?",
    answer_1: "Je dis rien",
    answer_2: "Je lui dis pour lui ouvrir les yeux",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 75,
    round_id: 2,
    name: "serais-tu capable de partir en vacances avec les amis de ton partenaire que tu n’aimes pas ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 76,
    round_id: 2,
    name: "tu trouves un portefeuille dans la rue. Le prends-tu ou bien passes-tu ton chemin ?",
    answer_1: "Je le prends",
    answer_2: "Je passe mon chemin",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 104,
    round_id: 3,
    name: "la vie de quelle personne ne voudriez-vous pas mener ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 105,
    round_id: 3,
    name: "d'après vous, qui serait capable de tuer quelqu'un ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 106,
    round_id: 3,
    name: "à qui feriez-vous le moins confiance pour garder un secret ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 107,
    round_id: 3,
    name: "qui estimez-vous le moins mature ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 108,
    round_id: 3,
    name: "avec qui avez-vous le moins d'affinités ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 109,
    round_id: 3,
    name: "avec qui pourriez-vous avoir des motifs de dispute ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 110,
    round_id: 3,
    name: "d'après vous, qui ici a le moins de chances de vivre quelque chose d’inattendu ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 111,
    round_id: 3,
    name: "avec qui vous sentez-vous le plus en concurrence ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 112,
    round_id: 3,
    name: "qui serait le plus susceptible de vous trahir pour ses intérêts ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 113,
    round_id: 3,
    name: "qui a les convictions les plus opposées aux vôtres ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 114,
    round_id: 3,
    name: "d'après vous, qui est le plus susceptible de faire les choses à moitié ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 115,
    round_id: 3,
    name: "qui serait le moins susceptible d’être honnête avec vous si la vérité peut vous blesser ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 116,
    round_id: 3,
    name: "qui vous semble le plus lâche ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 117,
    round_id: 3,
    name: "avec qui vous sentez-vous le moins en sécurité ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 118,
    round_id: 3,
    name: "avec qui vous sentez-vous le moins à l’aise ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 119,
    round_id: 3,
    name: "quelle personne vous inspire le moins confiance ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 120,
    round_id: 3,
    name: "d'après toi, qui a eu le moins de partenaires sexuels ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 121,
    round_id: 3,
    name: "avec qui as-tu le plus de chances d'avoir encore des relations dans vingt ans ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 122,
    round_id: 3,
    name: "qui te semble le plus susceptible de se rendre exécrable ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 123,
    round_id: 3,
    name: "d’après toi, qui a le moins de chance de s’épanouir professionnellement ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 124,
    round_id: 3,
    name: "qui te semble le plus égoïste ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 125,
    round_id: 3,
    name: "qui te paraît le plus narcissique ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 126,
    round_id: 3,
    name: "qui te fait le plus peur ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 127,
    round_id: 3,
    name: "qui t’a le plus déçu ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 128,
    round_id: 3,
    name: "avec qui as-tu le plus de mal à communiquer ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 129,
    round_id: 3,
    name: "qui cernes-tu le moins ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 130,
    round_id: 3,
    name: "qui te paraît le moins responsable ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 131,
    round_id: 3,
    name: "quelle est la personne t’accommodant le moins ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 132,
    round_id: 3,
    name: "avec qui ne partirais-tu pas en vacances ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 133,
    round_id: 3,
    name: "qui pourrait te faire le plus de mal ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 134,
    round_id: 3,
    name: "avec qui ressens-tu le plus de non-dits ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 135,
    round_id: 3,
    name: "à qui penses-tu le plus ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 136,
    round_id: 3,
    name: "à qui penses-tu le moins ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 137,
    round_id: 3,
    name: "qui ici serait le plus à même d’être de mauvaise foi pour ne pas admettre qu’il/qu’elle s’est trompé(e) ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 172,
    round_id: 4,
    name: "qui est la personne la plus complexée ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 173,
    round_id: 4,
    name: "qui est la personne la plus influençable ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 174,
    round_id: 4,
    name: "qui est la personne la plus susceptible ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 175,
    round_id: 4,
    name: "qui est la personne la plus frustrée ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 176,
    round_id: 4,
    name: "qui est la personne la plus narcissique ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 177,
    round_id: 4,
    name: "qui est la personne la plus dépensière ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 178,
    round_id: 4,
    name: "qui est la personne la plus fainéante ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 179,
    round_id: 4,
    name: "qui est la personne la plus opportuniste ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 180,
    round_id: 4,
    name: "qui est la personne la plus malheureuse ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 181,
    round_id: 4,
    name: "qui est la personne la plus rancunière ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 182,
    round_id: 4,
    name: "qui est la personne la plus soumise ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 183,
    round_id: 4,
    name: "qui est la personne la plus manipulatrice ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 184,
    round_id: 4,
    name: "qui est la personne la plus trouillarde ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 185,
    round_id: 4,
    name: "qui est la personne la plus matérialiste ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 186,
    round_id: 4,
    name: "qui est la personne la plus capricieuse ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 187,
    round_id: 4,
    name: "qui est la personne la plus désagréable ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 188,
    round_id: 4,
    name: "qui est la personne la plus anxieuse ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 189,
    round_id: 4,
    name: "qui est la personne la plus satisfaite d’elle-même ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 190,
    round_id: 4,
    name: "qui est la personne la plus pessimiste ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 191,
    round_id: 4,
    name: "qui est la personne la plus provocatrice ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 192,
    round_id: 4,
    name: "qui est la personne la plus susceptible de ne rien avoir à faire des autres ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 193,
    round_id: 4,
    name: "qui est la personne la plus dominatrice ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 194,
    round_id: 4,
    name: "qui est la personne la moins apte à se remettre d’une déception amoureuse ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 195,
    round_id: 4,
    name: "qui est la personne la plus indécise ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 196,
    round_id: 4,
    name: "qui est la personne la plus naïve ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 197,
    round_id: 4,
    name: "qui est la personne la plus décevante ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 198,
    round_id: 4,
    name: "qui est la personne la plus lâche ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 199,
    round_id: 4,
    name: "qui est la personne la plus hypocrite ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 200,
    round_id: 4,
    name: "qui serait le moins à même de surmonter une épreuve difficile ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
];
