import { Question, Round } from "../src/Interfaces";

export const rounds: Round[] = [
  {
    id: 1,
    name: "Personnalité",
  },
  {
    id: 2,
    name: "Situations",
  },
  {
    id: 3,
    name: "Représentations",
  },
  {
    id: 4,
    name: "Relations",
  },
];
export const questions: Question[] = [
  {
    id: 1,
    round_id: 1,
    name: "Tes vrais amis, tu les comptes ...",
    answer_1: "Sur les doigts d'une main",
    answer_2: "Sur les deux mains",
    answer_3: "Tu n'as pas assez de doigts pour les compter",
    answer_4: "Tu n'en as pas",
  },
  {
    id: 2,
    round_id: 1,
    name: "À quelle fréquence tu t'observes à travers un miroir ou des photos ?",
    answer_1: "Plus souvent que la plupart des gens",
    answer_2: "Moins souvent que la plupart des gens",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 3,
    round_id: 1,
    name: "Mens-tu ?",
    answer_1: "Plus que la plupart des gens",
    answer_2: "Moins que la plupart des gens",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 4,
    round_id: 1,
    name: "La vie à deux, pour toi c'est ...",
    answer_1: "Réconfortant",
    answer_2: "Excitant",
    answer_3: "Angoissant",
    answer_4: null,
  },
  {
    id: 5,
    round_id: 1,
    name: "On t'offre un cadeau qui ne te plaît pas, tu dis ...",
    answer_1: "Merci, ça me plaît beaucoup",
    answer_2: "Qu’est-ce que j’ai fait pour mériter ça ?",
    answer_3:
      "J’apprécie le geste mais ce n’est pas exactement ce dont j’ai l’utilité, peut-on l'échanger ?",
    answer_4: null,
  },
  {
    id: 6,
    round_id: 1,
    name: "Tu supportes le moins les gens ...",
    answer_1: "Vulgaires",
    answer_2: "Prétentieux",
    answer_3: "Fourbes",
    answer_4: null,
  },
  {
    id: 7,
    round_id: 1,
    name: "Selon toi, le vol ...",
    answer_1: "N’est jamais justifiable",
    answer_2: "Peut-être justifié",
    answer_3: "Est une action risquée pas forcément liée à la morale",
    answer_4: null,
  },
  {
    id: 8,
    round_id: 1,
    name: "En cas de conflit, es-tu plus enclin à ...",
    answer_1: "L’éviter",
    answer_2: "Rechercher un compromis",
    answer_3: "Prendre position et le défendre",
    answer_4: null,
  },
  {
    id: 9,
    round_id: 1,
    name: "Face à un problème, tu commences par ...",
    answer_1: "Rechercher des solutions par toi-même",
    answer_2: "Demander de l'aide",
    answer_3: "L'éviter et remettre à plus tard",
    answer_4: null,
  },
  {
    id: 10,
    round_id: 1,
    name: "Pour toi, la moins mauvaise société serait ...",
    answer_1: "Technocratique",
    answer_2: "Socialiste",
    answer_3: "Libérale",
    answer_4: null,
  },
  {
    id: 11,
    round_id: 1,
    name: "Selon toi, la tolérance ...",
    answer_1: "Est laxiste",
    answer_2: "Est un devoir",
    answer_3: "Est soumise à conditions",
    answer_4: null,
  },
  {
    id: 12,
    round_id: 1,
    name: "Pour toi, les inégalités sont ...",
    answer_1: "Insupportables",
    answer_2: "Inévitables",
    answer_3: "Souhaitables",
    answer_4: null,
  },
  {
    id: 13,
    round_id: 1,
    name: "Pour toi, la vérité est plutôt ...",
    answer_1: "Un poids",
    answer_2: "Un droit",
    answer_3: "Une affaire d'interprétation",
    answer_4: null,
  },
  {
    id: 14,
    round_id: 1,
    name: "En politique, les sujets qui t'intéressent sont plutôt ...",
    answer_1: "Économiques",
    answer_2: "Sociaux",
    answer_3: "Environnementaux",
    answer_4: null,
  },
  {
    id: 15,
    round_id: 1,
    name: "Tu préfères/préférerais que ton enfant soit ...",
    answer_1: "Gentil",
    answer_2: "Intelligent",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 17,
    round_id: 1,
    name: "Quelle qualité t'attire le plus chez un partenaire romantique ...",
    answer_1: "Le physique",
    answer_2: "L'intelligence",
    answer_3: "L'humour",
    answer_4: null,
  },
  {
    id: 18,
    round_id: 1,
    name: "Pour toi, le sexe ...",
    answer_1: "Est une forme d’amour",
    answer_2: "N’est pas forcément lié à l’amour",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 20,
    round_id: 1,
    name: "Pour toi la richesse matérielle c’est ...",
    answer_1: "Un péché",
    answer_2: "Une chance",
    answer_3: "Une récompense",
    answer_4: null,
  },
  {
    id: 21,
    round_id: 1,
    name: "Tu considères que la liberté d’expression doit être ...",
    answer_1: "Illimitée",
    answer_2: "Restreinte dans des espaces dédiés",
    answer_3: "Restreinte dans le contenu",
    answer_4: null,
  },
  {
    id: 22,
    round_id: 1,
    name: "Pour toi la religion est ...",
    answer_1: "Une opportunité de donner un sens à ta vie",
    answer_2: "L’ancêtre de la politique",
    answer_3: "Dépassée à notre époque",
    answer_4: null,
  },
  {
    id: 26,
    round_id: 1,
    name: "La principale qualité que tu attends d'un ami, c'est ...",
    answer_1: "La disponibilité",
    answer_2: "La confiance",
    answer_3: "La complicité",
    answer_4: null,
  },
  {
    id: 27,
    round_id: 1,
    name: "Pour toi, en ce moment, la soirée idéale serait plutôt ...",
    answer_1: "Au chaud à la maison",
    answer_2: "Un dîner en tête à tête",
    answer_3: "Une grande fête avec toutes tes relations",
    answer_4: null,
  },
  {
    id: 28,
    round_id: 1,
    name: "Parler est pour toi ...",
    answer_1: "Un plaisir",
    answer_2: "Un effort",
    answer_3: "Un vice",
    answer_4: null,
  },
  {
    id: 29,
    round_id: 1,
    name: "Si tu pouvais maîtriser un élément, lequel choisirais-tu ?",
    answer_1: "L’eau",
    answer_2: "La terre",
    answer_3: "Le feu",
    answer_4: "L’air",
  },
  {
    id: 30,
    round_id: 1,
    name: "Si tu étais un objet, ce serait ...",
    answer_1: "Une lame",
    answer_2: "Une horloge",
    answer_3: "Un coussin",
    answer_4: null,
  },
  {
    id: 31,
    round_id: 1,
    name: "Quelle qualité privilégies-tu chez un collègue de travail ?",
    answer_1: "La compétence technique",
    answer_2: "La compréhension globale de ce qu'il fait",
    answer_3: "La bonne entente",
    answer_4: "La réponse D",
  },
  {
    id: 32,
    round_id: 1,
    name: "En vacances, tu préfères ...",
    answer_1: "La plage",
    answer_2: "La montagne",
    answer_3: "Une grande ville",
    answer_4: null,
  },
  {
    id: 33,
    round_id: 1,
    name: "Si tu avais une journée de congé, tu la passerais ...",
    answer_1: "À voir tes amis",
    answer_2: "À pratiquer un hobby",
    answer_3: "À faire du shopping",
    answer_4: null,
  },
  {
    id: 34,
    round_id: 1,
    name: "Lors d'une discussion, tu es plutôt du genre à ...",
    answer_1: "Écouter",
    answer_2: "Argumenter et débattre",
    answer_3: "Aller dans le sens de la discussion",
    answer_4: null,
  },
  {
    id: 35,
    round_id: 1,
    name: "Pour toi, le progrès, c’est ...",
    answer_1: "Augmenter le niveau de confort",
    answer_2: "Pouvoir faire de nouvelles choses",
    answer_3: "Faire moins d’erreurs, être plus efficace",
    answer_4: null,
  },
  {
    id: 36,
    round_id: 1,
    name: "Quelle est ta saison préférée ?",
    answer_1: "Printemps",
    answer_2: "Été",
    answer_3: "Automne",
    answer_4: "Hiver",
  },
  {
    id: 37,
    round_id: 1,
    name: "Lorsque tu lis un livre, tu préfères ...",
    answer_1: "Te plonger dans un récit",
    answer_2: "Te cultiver",
    answer_3: "Tu ne lis pas de livre",
    answer_4: null,
  },
  {
    id: 38,
    round_id: 1,
    name: "Si tu étais un animal, tu serais ...",
    answer_1: "Un carnivore",
    answer_2: "Un herbivore",
    answer_3: "Un omnivore",
    answer_4: null,
  },
  {
    id: 39,
    round_id: 1,
    name: "À propos des réseaux sociaux, tu ...",
    answer_1: "Les adores",
    answer_2: "Les utilises pour rester en contact",
    answer_3: "Vis sans",
    answer_4: null,
  },
  {
    id: 40,
    round_id: 1,
    name: "En tant que chef d'entreprise, tu valoriserais davantage ...",
    answer_1: "L’activité",
    answer_2: "La rentabilité",
    answer_3: "L’ambiance de travail",
    answer_4: null,
  },
  {
    id: 41,
    round_id: 1,
    name: "Si tu pouvais observer (sans interaction) une période et un endroit donné dans le temps, irais-tu ...",
    answer_1: "Dans le passé",
    answer_2: "Dans le futur",
    answer_3: "Quelque part dans le présent",
    answer_4: null,
  },
  {
    id: 42,
    round_id: 1,
    name: "Tu préfères les activités sportives ...",
    answer_1: "En équipe",
    answer_2: "En solo",
    answer_3: "Ne pas faire de sport",
    answer_4: null,
  },
  {
    id: 43,
    round_id: 1,
    name: "En cas de stress, tu vas en priorité ...",
    answer_1: "Te défouler",
    answer_2: "Te distraire",
    answer_3: "Te confier",
    answer_4: null,
  },
  {
    id: 44,
    round_id: 1,
    name: "Tu estimes la valeur d’une personne à travers ...",
    answer_1: "Ses capacités",
    answer_2: "Ses accomplissements",
    answer_3: "Son comportement",
    answer_4: null,
  },
  {
    id: 45,
    round_id: 1,
    name: "Quelle qualité t'attire le plus chez un mentor ...",
    answer_1: "La patience",
    answer_2: "La bienveillance",
    answer_3: "La compétence",
    answer_4: null,
  },
  {
    id: 46,
    round_id: 1,
    name: "Face à une décision importante, tu vas plutôt ...",
    answer_1: "Suivre ton intuition",
    answer_2: "Analyser les faits et rationaliser",
    answer_3: "Consulter les conseils de tes proches",
    answer_4: null,
  },
  {
    id: 47,
    round_id: 1,
    name: "Lors d'une soirée entre amis, tu es plutôt ...",
    answer_1: "L’animateur",
    answer_2: "Le comique",
    answer_3: "Le discret",
    answer_4: null,
  },
  {
    id: 48,
    round_id: 1,
    name: "Si tu étais un aliment, lequel serais-tu ? ...",
    answer_1: "Un bon burger bien gras",
    answer_2: "Un brocoli à la vapeur",
    answer_3: "Un risotto au poulet",
    answer_4: null,
  },
  {
    id: 50,
    round_id: 1,
    name: "Tu as parfois l'impression de manquer ...",
    answer_1: "D'humilité",
    answer_2: "De culture",
    answer_3: "D'initiative",
    answer_4: null,
  },
  {
    id: 51,
    round_id: 1,
    name: "Les relations que tu chéris le plus sont ...",
    answer_1: "Les plus longues",
    answer_2: "Les plus intenses",
    answer_3: "Les plus exclusives",
    answer_4: null,
  },
  {
    id: 52,
    round_id: 1,
    name: "Ta priorité en ce moment c’est ...",
    answer_1: "Le travail",
    answer_2: "Tes projets persos (non pro)",
    answer_3: "Tes proches",
    answer_4: "Les plus exclusives",
  },
  {
    id: 53,
    round_id: 1,
    name: "Tu préfère être dans ...",
    answer_1: "L'ombre",
    answer_2: "La lumière",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 54,
    round_id: 1,
    name: "Tu abordes plutôt la vie ...",
    answer_1: "Avec rigueur",
    answer_2: "Avec légèreté",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 55,
    round_id: 1,
    name: "Pour toi la triche ...",
    answer_1: "Prive du mérite",
    answer_2: "Fait partie du jeu",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 56,
    round_id: 1,
    name: "Tu abordes principalement la vie avec ...",
    answer_1: "Logique",
    answer_2: "Intuition",
    answer_3: "Morale",
    answer_4: null,
  },
  {
    id: 57,
    round_id: 1,
    name: "Tu as plutôt une mémoire ...",
    answer_1: "Visuelle",
    answer_2: "Auditive",
    answer_3: "Kinesthésique",
    answer_4: null,
  },
  {
    id: 58,
    round_id: 1,
    name: "Pour toi, le meilleur cadeau c’est ...",
    answer_1: "Un bien tangible",
    answer_2: "Une expérience éphémère",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 59,
    round_id: 1,
    name: "Selon toi, la plus grande qualité humaine est ...",
    answer_1: "L’altruisme",
    answer_2: "La créativité",
    answer_3: "La persévérance",
    answer_4: null,
  },
  {
    id: 60,
    round_id: 1,
    name: "Selon toi, pour réussir, il faut principalement ...",
    answer_1: "Du talent",
    answer_2: "Du travail",
    answer_3: "De la chance",
    answer_4: null,
  },
  {
    id: 61,
    round_id: 1,
    name: "Selon toi, le plus grand frein à la justice est ...",
    answer_1: "L’inégalité",
    answer_2: "La corruption",
    answer_3: "Le manque d’éducation",
    answer_4: null,
  },
  {
    id: 62,
    round_id: 1,
    name: "La rémunération doit être accordée en priorité selon ...",
    answer_1: "La valeur ajoutée",
    answer_2: "Le temps travaillé",
    answer_3: "La pénibilité",
    answer_4: "Les risques pris",
  },
  {
    id: 63,
    round_id: 1,
    name: "tu préfères ...",
    answer_1: "Ne jamais perdre",
    answer_2: "Ne jamais gagner",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 63,
    round_id: 1,
    name: "Tu préfères ...",
    answer_1: "Ne jamais perdre",
    answer_2: "Ne jamais gagner",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 64,
    round_id: 1,
    name: "Tu es plutôt ...",
    answer_1: "Cigale",
    answer_2: "Fourmi",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 1111,
    round_id: 1,
    name: "Tu es plutôt ...",
    answer_1: "Sucré",
    answer_2: "Salé",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 1112,
    round_id: 1,
    name: "Tu préfère construire quelque chose de...",
    answer_1: "Beau",
    answer_2: "Robuste",
    answer_3: "Utile",
    answer_4: null,
  },
  {
    id: 65,
    round_id: 2,
    name: "Tu as une opportunité de carrière exceptionnelle à l'étranger, mais cela signifierait laisser derrière toi ta famille et tes amis proches pour une période non négligeable. Que choisis-tu ?",
    answer_1: "Je pars",
    answer_2: "Je reste",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 66,
    round_id: 2,
    name: "Ton ami(e) a une altercation avec des inconnus. Prends-tu instinctivement son parti sachant qu’il/elle peut être en tort ?",
    answer_1: "Je prends son parti",
    answer_2: "Je reste en retrait",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 67,
    round_id: 2,
    name: "Tu découvres qu'un ami très cher t'a caché un événement important de sa vie. Restes-tu son ami ?",
    answer_1: "Je reste son ami",
    answer_2: "Je m'en éloigne",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 68,
    round_id: 2,
    name: "Tu as promis à quelqu'un de garder un secret. Gardes-tu le silence au risque de nuire à une autre personne ?",
    answer_1: "Je garde le silence",
    answer_2: "Je dévoile le secret",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 70,
    round_id: 2,
    name: "Tu es en désaccord avec un aîné de ta famille sur une question politique très sensible. Défends-tu ton point de vue au risque de te mettre cette personne à dos ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 71,
    round_id: 2,
    name: "Un ami te demande de le couvrir en mentant à sa moitié au sujet de sa présence à un événement. Acceptes-tu de mentir pour lui ou refuses-tu de participer à la duperie ?",
    answer_1: "J'accepte",
    answer_2: "Je refuse",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 72,
    round_id: 2,
    name: "Un aîné de ta famille fait des commentaires désobligeants sur ton partenaire. Confrontes-tu cette personne ou ignores-tu les commentaires pour éviter les conflits ?",
    answer_1: "Je la confronte",
    answer_2: "Je laisse couler",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 73,
    round_id: 2,
    name: "Ton ami heureux en ménage est sur le point de commettre un adultère. Le dissuades-tu ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 74,
    round_id: 2,
    name: "Ton partenaire tient un journal intime. Ce journal est laissé sans surveillance, le consultes-tu sans son consentement ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 75,
    round_id: 2,
    name: "Tu organises une fête et un invité boit trop, devenant gênant pour les autres. Irais-tu jusqu’à le calmer devant tout le monde ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 76,
    round_id: 2,
    name: "Tu n’arrives plus à faire l’amour et n’éprouves plus aucun désir. Autorises-tu ton partenaire à assouvir ses besoins sexuels avec d’autres personnes ? (Il/Elle n’est pas la cause de ton absence de libido)",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 77,
    round_id: 2,
    name: "Un aîné de votre famille vous critique sévèrement sur votre mode de vie lors d’un repas. Lui réponds-tu ou gardes-tu ton calme pour ne pas envenimer les choses ?",
    answer_1: "Je me défends",
    answer_2: "Je laisse couler",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 78,
    round_id: 2,
    name: "Tu as eu des relations sexuelles avec un(e) ami(e), t’éloignes-tu de cette personne une fois en couple ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 79,
    round_id: 2,
    name: "Tu as un ami qui ne cesse de se plaindre de ses problèmes, mais ne semble jamais prendre de mesures pour les résoudre. Lui avoues-tu le fond de ta pensée ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 80,
    round_id: 2,
    name: "Tu gagnes une grosse somme d’argent au casino quand tes amis ont perdu à la même soirée. Rembourses-tu leur perte si ton gain le permet ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 81,
    round_id: 2,
    name: "Mettrais-tu un terme à une relation si toi et ton partenaire n’étiez pas d’accord sur l’idée d’avoir des enfants ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 82,
    round_id: 2,
    name: "Tu constates qu’un proche s’éloigne peu à peu de toi. Tu le laisses s'éloigner ou tu tentes de renouer avec la personne ?",
    answer_1: "J'essaye de rattraper la personne",
    answer_2: "Je m'en éloigne",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 84,
    round_id: 2,
    name: "Tu apprends que ton ami(e) subit des violences conjugales. Agis-tu même si cet(te) ami(e) te demande de rester en dehors de ça ?",
    answer_1: "Je respecte son choix",
    answer_2: "J'interviens pour essayer de stopper les violences",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 86,
    round_id: 2,
    name: "Tu es condamné pour un crime. Dénonces-tu tes associés contre une remise de peine significative ?",
    answer_1: "Je balance",
    answer_2: "Je garde le silence",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 87,
    round_id: 2,
    name: "Un ami te prête un objet et tu le casses accidentellement. Cependant ton ami ne se souvient pas de l’état de l’objet et pourrait croire que le défaut était déjà là avant de te le prêter. Avoues-tu ta maladresse ou fais-tu mine de rien ?",
    answer_1: "J'avoue",
    answer_2: "Je fais mine de rien",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 89,
    round_id: 2,
    name: "Serais-tu capable de partir en vacances avec les amis de ton partenaire que tu n’aimes pas ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 90,
    round_id: 2,
    name: "Tu trouves un portefeuille dans la rue. Le prends-tu ou bien passes-tu ton chemin ?",
    answer_1: "Je le prends",
    answer_2: "Je passe mon chemin",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 91,
    round_id: 2,
    name: "Tu es invité à un dîner et la nourriture est très mauvaise. Fais-tu des commentaires ou gardes-tu tes impressions pour toi ?",
    answer_1: "Je me permets un commentaire",
    answer_2: "Je garde mes impressions pour moi",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 92,
    round_id: 2,
    name: "Au début d’une relation amoureuse, caches-tu ce que ton partenaire pourrait trouver agaçant chez toi ou bien joues-tu carte sur table ?",
    answer_1: "Je joue carte sur table",
    answer_2: "J'essaye de faire bonne figure",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 93,
    round_id: 2,
    name: "Ton partenaire insiste pour regarder un film que tu détestes. Acceptes-tu de le regarder pour lui faire plaisir ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 94,
    round_id: 2,
    name: "Tu es témoin d'une réprimande sévère d’un parent à son enfant dans un lieu public. Interviens-tu ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 95,
    round_id: 2,
    name: "Tu es invité à un événement auquel tu ne veux pas aller, te forces-tu pour ne pas froisser l’organisateur/trice ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 96,
    round_id: 2,
    name: "Ton meilleur ami est en couple avec quelqu'un que tu méprises. Caches-tu cette aversion ?",
    answer_1:
      "Oui, je ne peux pas le laisser se saboter par quelqu'un d'aussi médiocre",
    answer_2: "Non, je le laisse trouver son bonheur comme il veut",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 97,
    round_id: 2,
    name: "Tu as commis une erreur majeure au travail qui pourrait coûter cher à ton entreprise. Es-tu honnête ou essaies-tu de la cacher ?",
    answer_1: "Je le déclare",
    answer_2: "J'essaye de le cacher",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 98,
    round_id: 2,
    name: "Tu es invité à un événement familial important, mais tu as un engagement professionnel majeur le même jour. Que priorises-tu ?",
    answer_1:
      "La famille, à quoi bon si je ne suis pas là dans ces moments là ?",
    answer_2: "La carrière, je pourrais toujours voir ma famille plus tard",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 99,
    round_id: 2,
    name: "Tu es témoin d'une conversation où quelqu'un dénigre ou discrimine une personne en raison de sa religion, de sa race ou de son orientation sexuelle. Interviens-tu pour défendre la personne offensée ou restes-tu en retrait ?",
    answer_1: "J'interviens",
    answer_2: "Je reste en retrait, ça ne me regarde pas",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 100,
    round_id: 2,
    name: "Tu as l'opportunité de tricher à un examen important, ce qui pourrait améliorer considérablement tes résultats. Choisis-tu l'intégrité ou la réussite à tout prix ?",
    answer_1: "Je triche, pour réussir il faut être prêt à tout",
    answer_2:
      "Je reste intègre, en trichant ma réussite n'en vaudra pas la peine",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 101,
    round_id: 2,
    name: "Quelqu'un dont tu reconnais le visage t’aborde avec familiarité. Après dix minutes de conversation, tu n'es toujours pas en mesure de te souvenir de son nom. Lui demandes-tu de te le rappeler ?",
    answer_1: "Je fais comme si je le reconnaissais",
    answer_2: "Je lui demande de me rappeler qui il est",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 102,
    round_id: 2,
    name: "Tu remarques qu’une personne âgée peine à traverser la rue. L'aides-tu spontanément ou continues-tu ton chemin sans intervenir ?",
    answer_1: "Je l'aide",
    answer_2: "Je continue mon chemin",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 103,
    round_id: 2,
    name: "Un ami te demande de lui prêter de l'argent, mais tu sais qu'il a des habitudes de dépenses irresponsables. Accèdes-tu à sa demande ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 104,
    round_id: 2,
    name: "Tu es passager d’une voiture que conduit ton ami en retour de soirée arrosée, au milieu d’une route déserte. Quelqu’un surgit et la voiture renverse la personne de plein fouet. Ton ami te demande de garder cet incident sous silence, que fais-tu ?",
    answer_1: "Je garde le silence",
    answer_2: "Je confesse",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 105,
    round_id: 2,
    name: "Ton collègue de travail prend tout le crédit pour un projet sur lequel tu as travaillé dur. Dévoiles-tu la vérité à ton supérieur ou laisses-tu la situation telle quelle ?",
    answer_1: "Je dévoile la vérité",
    answer_2: "Je ne dis rien",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 106,
    round_id: 2,
    name: "Tu es au cinéma et quelqu'un à côté de toi parle constamment au téléphone. Lui demandes-tu de se taire ou supportes-tu la situation en silence ?",
    answer_1: "Je lui demande de se taire",
    answer_2: "Je subis en silence",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 107,
    round_id: 2,
    name: "Tu es invité à une soirée où tu sais que des personnes présentes ont des opinions politiques très différentes des tiennes. Y participes-tu malgré les divergences ou trouves-tu une excuse pour ne pas y aller ?",
    answer_1: "J'y vais",
    answer_2: "Je trouve une excuse",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 108,
    round_id: 2,
    name: "Tu es au restaurant avec des amis et il est décidé de diviser l’addition à parts égales alors que tu as largement moins consommé. Te manifestes-tu pour payer uniquement ta part ?",
    answer_1: "Je demande à payer ce que j'ai consommé",
    answer_2: "Je paie comme tout le monde",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 109,
    round_id: 2,
    name: "Ton enfant dépasse les bornes et te manque ouvertement de respect. Lui expliques-tu calmement que son comportement est inapproprié ou réagis-tu émotionnellement pour lui faire comprendre qu’il a dépassé les bornes ?",
    answer_1: "Je lui explique calmement",
    answer_2: "Je lui montre en réagissant émotionnellement",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 110,
    round_id: 2,
    name: "On te vole un bijou. Sachant que tu ne le récupéreras jamais, le ferais-tu disparaître à distance si tu en avais la faculté ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 111,
    round_id: 2,
    name: "Face à un danger mortel, entre sauver un proche et un groupe d’inconnus, que ferais-tu ?",
    answer_1: "Je sauve mon proche",
    answer_2: "Je sauve les inconnus",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 112,
    round_id: 2,
    name: "Debout dans les transports avec deux amis, tu rentres chez toi après une dure journée. Une seule place assise se libère à côté de toi, t’assois-tu ?",
    answer_1: "Je m'assois",
    answer_2: "Je reste debout",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 113,
    round_id: 2,
    name: "Si un génie te propose de te dire quand et comment tu vas mourir, refuses-tu ?",
    answer_1: "Je refuse",
    answer_2: "J'accepte",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 114,
    round_id: 2,
    name: "Dans Matrix, choisirais-tu la pilule bleue ou la pilule rouge ?",
    answer_1: "Pilule bleue",
    answer_2: "Pilule rouge",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 115,
    round_id: 2,
    name: "Tu roules en ville à 50 km/h quand un enfant traverse sans regarder. Il t’est impossible de l’éviter sauf en te déportant sur la voie cyclable où un cycliste arrive en face. Restes-tu sur la route ou sacrifies-tu le cycliste ?",
    answer_1: "Je reste sur la route",
    answer_2: "Je me déporte au détriment du cycliste",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 116,
    round_id: 2,
    name: "Tu croises une vieille connaissance dans la rue mais elle ne t'aperçoit pas, l’interpelles-tu pour discuter ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 117,
    round_id: 2,
    name: "Votre enfant se fait tuer. Laissez-vous la justice se charger du coupable ou faites-vous justice vous-même ?",
    answer_1: "Justice",
    answer_2: "Vengeance",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 118,
    round_id: 2,
    name: "Tu as la possibilité de modifier un moment clé de ton passé. Tentes-tu de le changer, sachant que cela pourrait avoir des conséquences imprévisibles sur le présent ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 119,
    round_id: 2,
    name: "Si tu pouvais complètement effacer de ta mémoire certains éléments de ta vie, le ferais-tu ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 120,
    round_id: 2,
    name: "Si tu pouvais te cloner tel que tu es actuellement, le ferais-tu ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 121,
    round_id: 2,
    name: "On te propose de télécharger ta conscience dans une machine pour vivre après ta mort. Tu le fais ou pas ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 122,
    round_id: 2,
    name: "Une technologie permet à certaines personnes de transposer leur conscience dans un ordinateur (avec la capacité de traitement adéquate pour soutenir toutes les informations disponibles sur internet). Les considères-tu toujours comme humains après l’opération ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 123,
    round_id: 2,
    name: "On te propose une modification qui peut supprimer tes biais cognitifs. Tu l’acceptes ou pas ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 124,
    round_id: 2,
    name: "Tu peux parler couramment toutes les langues du monde, mais tu perds ton sens de l’humour. Tu acceptes ou pas ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 125,
    round_id: 2,
    name: "Une marque te propose de te tatouer leur logo en échange de produits gratuits à vie. Tu acceptes ou pas ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 126,
    round_id: 2,
    name: "On t’offre un an de nourriture gratuite au restaurant de ton choix, mais tu ne pourras rien manger ailleurs pendant cette période. Tu le fais ou pas ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 127,
    round_id: 2,
    name: "Serais-tu prêt.e à suivre ton.ta partenaire pour faire ta vie ailleurs ?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  // {
  //   id: 2221,
  //   round_id: 2,
  //   name: "Un candidat défend tes intérêts, au détriment de la situation globale du pays. Tu votes pour lui ou pas ?",
  //   answer_1: "Oui",
  //   answer_2: "Non",
  //   answer_3: null,
  //   answer_4: null,
  // },
  // {
  //   id: 2222,
  //   round_id: 2,
  //   name: "Un nouveau confinement covid est déclaré. Le respectes-tu ?",
  //   answer_1: "Oui",
  //   answer_2: "Non",
  //   answer_3: null,
  //   answer_4: null,
  // },
  // {
  //   id: 2223,
  //   round_id: 2,
  //   name: "Si tu pouvais contraindre les gens à voter pour le parti que tu soutiens, le ferais-tu ?",
  //   answer_1: "Oui",
  //   answer_2: "Non",
  //   answer_3: null,
  //   answer_4: null,
  // },
  {
    id: 2224,
    round_id: 2,
    name: "Si tu pouvais retourner dans le passé et tuer Hitler enfant, le ferais-tu?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },
  {
    id: 2225,
    round_id: 2,
    name: "Si tu gagnes au loto, est-ce que tu arrête de travailler?",
    answer_1: "Oui",
    answer_2: "Non",
    answer_3: null,
    answer_4: null,
  },

  {
    id: 131,
    round_id: 3,
    name: "Qui serait le·la plus enclin·e à partir avant la fin du jeu à cause d’une réponse qui ne lui plaît pas ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 137,
    round_id: 3,
    name: "Qui te semble être le·la plus matérialiste ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 139,
    round_id: 3,
    name: "Qui te semble être le·la plus anxieux·se ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 140,
    round_id: 3,
    name: "Qui te semble être le·la plus satisfait·e de sa vie ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 141,
    round_id: 3,
    name: "Qui te semble être le·la plus pessimiste ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 142,
    round_id: 3,
    name: "Qui te semble être le·la plus provocateur·rice ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 143,
    round_id: 3,
    name: "Qui te semble être le·la plus indifférent·e aux autres ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 144,
    round_id: 3,
    name: "Qui te semble être le·la plus dominant·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 145,
    round_id: 3,
    name: "Qui te semble être le·la plus indécis·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 146,
    round_id: 3,
    name: "Qui te semble être le·la plus naïf·ve ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 147,
    round_id: 3,
    name: "Qui se remet le moins en question ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 148,
    round_id: 3,
    name: "Qui vend le plus de rêve ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 150,
    round_id: 3,
    name: "Qui a l’esprit le moins torturé selon toi ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 153,
    round_id: 3,
    name: "Qui te semble être le·la plus enclin·e à fuir les confrontations ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 154,
    round_id: 3,
    name: "Qui te semble être le·la plus réactif·ve sous le coup de l’émotion ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 155,
    round_id: 3,
    name: "Qui te semble être le·la plus sujet·te aux excès de confiance ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 156,
    round_id: 3,
    name: "Qui te semble être le·la plus distrait·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 157,
    round_id: 3,
    name: "Qui te semble être le·la plus précipité·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 158,
    round_id: 3,
    name: "Qui te semble être le·la plus pressé·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 159,
    round_id: 3,
    name: "Qui te semble être le·la plus préoccupé·e par l’apparence ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 160,
    round_id: 3,
    name: "Qui te semble être le·la plus enclin·e à se comparer aux autres ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 161,
    round_id: 3,
    name: "Qui te semble être le·la plus désorganisé·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 162,
    round_id: 3,
    name: "Qui te semble être le·la plus affecté·e par les jugements extérieurs ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 163,
    round_id: 3,
    name: "Qui te semble être le·la plus résistant·e aux changements, même bénéfiques ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 164,
    round_id: 3,
    name: "Qui te semble être le·la plus sujet·te à dramatiser ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 165,
    round_id: 3,
    name: "Qui te semble être le·la plus négligent·e dans l’entretien de ses relations ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 166,
    round_id: 3,
    name: "Qui te semble être le·la plus influencé·e par des peurs irrationnelles ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 167,
    round_id: 3,
    name: "Qui subit le plus la solitude ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 168,
    round_id: 3,
    name: "Qui te semble être le·la plus observateur·rice ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 169,
    round_id: 3,
    name: "Qui te semble être le·la plus cultivé·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 170,
    round_id: 3,
    name: "Qui te semble être le·la plus secret·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 171,
    round_id: 3,
    name: "Qui te semble être le·la plus tolérant·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 172,
    round_id: 3,
    name: "Qui te semble être le·la plus sensuel·le ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 173,
    round_id: 3,
    name: "Qui te semble être le·la plus altruiste ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 174,
    round_id: 3,
    name: "Qui te semble être le·la plus charismatique ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 175,
    round_id: 3,
    name: "Qui te semble être le·la plus charmeur·se ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 176,
    round_id: 3,
    name: "Qui te semble être le·la plus intelligent·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 177,
    round_id: 3,
    name: "Qui te semble être le·la moins émotif·ve ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 178,
    round_id: 3,
    name: "Qui te semble être le·la plus impénétrable ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 179,
    round_id: 3,
    name: "Qui te semble être le·la plus extraverti·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 180,
    round_id: 3,
    name: "Qui te semble être le·la plus insaisissable ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 181,
    round_id: 3,
    name: "Qui te semble être le·la plus élégant·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 182,
    round_id: 3,
    name: "Qui te semble être le·la plus créatif·ve ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 183,
    round_id: 3,
    name: "Qui a le mental le plus solide ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 184,
    round_id: 3,
    name: "Qui a traversé les épreuves les plus difficiles ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 185,
    round_id: 3,
    name: "Qui serait le·la plus susceptible de vomir d’amour ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 186,
    round_id: 3,
    name: "Selon toi, qui ferait primer le bien-être sur les valeurs comme la liberté, l’égalité ou l’honneur ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 187,
    round_id: 3,
    name: "De manière générale, qui te semble être le·la plus exigeant·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 188,
    round_id: 3,
    name: "Qui te semble être le·la plus exigeant·e envers elle-même ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 189,
    round_id: 3,
    name: "De manière générale, qui te semble être le·la plus dur·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 190,
    round_id: 3,
    name: "Qui te semble être le·la plus dur·e envers elle-même ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 191,
    round_id: 3,
    name: "Qui te semble être le·la plus sérieux·se ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 192,
    round_id: 3,
    name: "Qui a la plus grande capacité à prendre sur soi dans une situation grave ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 193,
    round_id: 3,
    name: "Qui a une image intérieure qui diffère le plus de celle qu’il·elle reflète aux autres ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 194,
    round_id: 3,
    name: "Qui te semble être le·la plus orienté·e solutions ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 195,
    round_id: 3,
    name: "Qui te semble être le·la plus transparent·e dans ses intentions ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 196,
    round_id: 3,
    name: "Qui te semble être le·la plus authentique, fidèle à ses valeurs ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 197,
    round_id: 3,
    name: "Qui te semble être le·la plus flexible dans ses attentes ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 198,
    round_id: 3,
    name: "Qui te semble être le·la plus aventureux·se dans ses projets ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 199,
    round_id: 3,
    name: "Qui te semble être le·la plus inspiré·e par la nouveauté ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 200,
    round_id: 3,
    name: "Qui te semble être le·la plus en quête de sens dans sa vie ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 201,
    round_id: 3,
    name: "Qui te semble être le·la plus loyal·e dans ses relations ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 202,
    round_id: 3,
    name: "Qui te semble être le·la plus sensible à l’injustice ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 203,
    round_id: 3,
    name: "Qui te semble être le·la plus structuré·e dans ses pensées ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 204,
    round_id: 3,
    name: "Qui te semble être le·la plus intègre, même sous pression ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 205,
    round_id: 3,
    name: "Qui te semble être le·la plus stimulé·e par les défis ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 206,
    round_id: 3,
    name: "Qui te semble être le·la plus serein·e face à l’incertitude ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 207,
    round_id: 3,
    name: "Qui te semble être le·la plus imaginatif·ve pour les projets futurs ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 208,
    round_id: 3,
    name: "Qui te semble être le·la plus bienveillant·e envers elle-même ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 209,
    round_id: 3,
    name: "Qui te semble être le·la plus innovant·e dans ses idées ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 210,
    round_id: 3,
    name: "Qui te semble être le·la plus capable de prendre du recul sur elle-même ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 211,
    round_id: 3,
    name: "Qui te semble être le·la plus en harmonie avec ses émotions ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 212,
    round_id: 3,
    name: "Qui te semble être le·la plus inquiet·ète ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 213,
    round_id: 3,
    name: "Qui te semble être le·la plus honnête ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 214,
    round_id: 3,
    name: "Qui ici se contente du moins de choses ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 215,
    round_id: 3,
    name: "Qui est le·la plus susceptible de respecter ses propres règles plutôt que celles de la société lorsqu’elles entrent en conflit ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 216,
    round_id: 3,
    name: "D’après toi, qui masque le mieux ses peines ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 217,
    round_id: 3,
    name: "Qui te semble le·la plus doué·e pour résoudre des problèmes complexes ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 218,
    round_id: 3,
    name: "Quelle personne te semble le·la plus compétent·e pour résoudre des conflits ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 219,
    round_id: 3,
    name: "D’après toi, qui est le·la plus apte à prendre des décisions rationnelles ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 220,
    round_id: 3,
    name: "Qui te semble le·la plus courageux·se ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 221,
    round_id: 3,
    name: "Qui est le·la plus romantique ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 222,
    round_id: 3,
    name: "Quelle personne te semble le·la plus résiliente ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 223,
    round_id: 3,
    name: "Qui te semble être le·la plus enclin·e à prendre des risques audacieux ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 224,
    round_id: 3,
    name: "D’après toi, qui serait le·la meilleur·e conseiller·ère en relations amoureuses ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 225,
    round_id: 3,
    name: "D’après toi, qui serait le·la plus calme dans une situation d’urgence ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 226,
    round_id: 3,
    name: "Qui te semble être le·la plus calme en situation de conflit ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 227,
    round_id: 3,
    name: "Qui mettrait le plus de temps à se remettre d’une déception amoureuse ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 228,
    round_id: 3,
    name: "Qui te semble être le·la plus convaincant·e ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 229,
    round_id: 3,
    name: "Qui est la personne la plus complexe ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 230,
    round_id: 3,
    name: "Qui est le·la plus généreux·se ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 231,
    round_id: 3,
    name: "Qui semble être le plus sincère ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 232,
    round_id: 3,
    name: "Qui est la personne la plus insouciante ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 233,
    round_id: 3,
    name: "Qui a eu le plus gros chagrin d’amour ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 3331,
    round_id: 3,
    name: "Qui te semble être le·la plus laxiste ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 3332,
    round_id: 3,
    name: "Qui est le.la plus gentil.lle ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 3333,
    round_id: 3,
    name: "Qui a le plus de vitalité ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 3334,
    round_id: 3,
    name: "Qui semble le plus susceptible de sacrifier ses intérêts pour quelqu’un d’autre ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 3335,
    round_id: 3,
    name: "Qui semble le plus susceptible d’être agacé par les mendiants?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 247,
    round_id: 4,
    name: "La vie de quelle joueur/joueuse ne voudrais-tu pas mener ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 248,
    round_id: 4,
    name: "D'après toi, qui serait le plus capable de tuer quelqu'un ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 249,
    round_id: 4,
    name: "À qui ferais-tu le moins confiance pour garder un secret ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 251,
    round_id: 4,
    name: "Qui te semble être le plus différent de toi ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 252,
    round_id: 4,
    name: "Avec qui pourrais-tu avoir des motifs de dispute ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 253,
    round_id: 4,
    name: "D'après toi, qui ici a le moins de chances de vivre quelque chose d’inattendu ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 256,
    round_id: 4,
    name: "Qui a les convictions les plus opposées aux tiennes ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 258,
    round_id: 4,
    name: "Qui serait le moins susceptible d’être honnête avec toi si la vérité peut te blesser ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 259,
    round_id: 4,
    name: "Avec qui te sens-tu le moins en sécurité ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 260,
    round_id: 4,
    name: "Avec qui te sens-tu le moins à l’aise ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 261,
    round_id: 4,
    name: "Quelle personne te paraît la plus froide ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 262,
    round_id: 4,
    name: "D'après toi, qui est le moins intéressé par la sexualité ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 263,
    round_id: 4,
    name: "Avec qui as-tu le plus de chances d'avoir encore des relations dans vingt ans ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 264,
    round_id: 4,
    name: "Qui te semble le plus susceptible de se rendre exécrable à cause d’une déconvenue ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 266,
    round_id: 4,
    name: "D’après toi, qui a le moins de chance de s’épanouir professionnellement ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 267,
    round_id: 4,
    name: "Qui te semble le plus égoïste ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 268,
    round_id: 4,
    name: "Qui te paraît le plus égocentré ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 269,
    round_id: 4,
    name: "Qui te fait le plus peur ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 270,
    round_id: 4,
    name: "Qui t’a le plus déçu ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 271,
    round_id: 4,
    name: "Avec qui as-tu le plus de mal à communiquer ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 272,
    round_id: 4,
    name: "Qui cernes-tu le moins ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 273,
    round_id: 4,
    name: "Qui te paraît le moins responsable ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 274,
    round_id: 4,
    name: "Avec qui ne partirais-tu pas en vacances ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 275,
    round_id: 4,
    name: "Qui pourrait te faire le plus de mal ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 276,
    round_id: 4,
    name: "Avec qui ressens-tu le plus de non-dits ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 277,
    round_id: 4,
    name: "Qui te fais le moins d’effet ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 278,
    round_id: 4,
    name: "À qui penses-tu le plus ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 279,
    round_id: 4,
    name: "À qui penses-tu le moins ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 280,
    round_id: 4,
    name: "Qui ici serait le plus à même d’être de mauvaise foi pour ne pas admettre qu’il/qu’elle s’est trompé(e) ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 281,
    round_id: 4,
    name: "Qui souffrirait le plus d’avoir un enfant LGBT ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 282,
    round_id: 4,
    name: "Qui est le moins reconnaissant envers sa chance ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 283,
    round_id: 4,
    name: "Quelle personne t’inspire le plus confiance ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 284,
    round_id: 4,
    name: "Qui te satisfait le plus ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 285,
    round_id: 4,
    name: "Quelle personne te paraît la plus ambitieuse ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 286,
    round_id: 4,
    name: "Quel visage te fait le plus penser à un animal ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 287,
    round_id: 4,
    name: "D'après toi, qui a eu le plus d'aventures sexuelles ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 288,
    round_id: 4,
    name: "Qui te paraît le plus mature ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 289,
    round_id: 4,
    name: "D'après toi, qui a le plus beau sourire ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 290,
    round_id: 4,
    name: "D’après toi, qui sera le plus accompli dans 10 ans ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 291,
    round_id: 4,
    name: "Qui aurait, selon toi, le plus de succès en tant que leader politique ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 292,
    round_id: 4,
    name: "Avec qui aimerais-tu partir en voyage ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 293,
    round_id: 4,
    name: "Qui te ressemble le plus ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 294,
    round_id: 4,
    name: "Qui respectes-tu le plus ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 295,
    round_id: 4,
    name: "Quelle est la personne avec qui tu as la relation la plus intense ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 296,
    round_id: 4,
    name: "Qui te semble le plus créatif ou imaginatif ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 297,
    round_id: 4,
    name: "Avec qui te sens-tu le plus en sécurité ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 298,
    round_id: 4,
    name: "Avec qui te sens-tu le plus à l’aise ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 299,
    round_id: 4,
    name: "D’après toi, qui a le plus de chance de devenir très riche ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 300,
    round_id: 4,
    name: "Avec qui pourrais-tu avoir les conversations les plus profondes et significatives ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 301,
    round_id: 4,
    name: "Avec qui partagerais-tu tes joies et tes peines en premier ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 302,
    round_id: 4,
    name: "Qui te comprend le mieux ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 303,
    round_id: 4,
    name: "Les pensées de quel participant(e) préférerais-tu pouvoir lire ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 304,
    round_id: 4,
    name: "Quelle est la personne te paraissant la plus fiable ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 305,
    round_id: 4,
    name: "Qui te donne le plus d’espoir ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 306,
    round_id: 4,
    name: "Qui te fait le plus rire ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 307,
    round_id: 4,
    name: "Qui partage le plus ta vision du monde ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 308,
    round_id: 4,
    name: "Qui t’apaise le plus ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 309,
    round_id: 4,
    name: "Qui choisit le mieux ses combats ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 310,
    round_id: 4,
    name: "Qui a le meilleur style ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 311,
    round_id: 4,
    name: "Qui a le plus d’égo ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 312,
    round_id: 4,
    name: "Si tu devais cacher un corps, qui appellerais-tu pour t’aider ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 313,
    round_id: 4,
    name: "Avec qui échangerais-tu ta vie pendant une journée ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 314,
    round_id: 4,
    name: "Qui a la réflexion la plus proche de la tienne ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 315,
    round_id: 4,
    name: "Qui a des valeurs les plus similaires aux tiennes ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 316,
    round_id: 4,
    name: "Qui aurais-tu élu·e comme délégué·e de classe ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 317,
    round_id: 4,
    name: "Qui s’investit le plus dans ses relations amicales ou amoureuses ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 318,
    round_id: 4,
    name: "Qui est la personne la plus gentille ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 319,
    round_id: 4,
    name: "Qui est la personne la plus bienveillante ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 320,
    round_id: 4,
    name: "À qui fais-tu le plus confiance ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 321,
    round_id: 4,
    name: "Qui a la plus belle plume ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 322,
    round_id: 4,
    name: "Qui écoute la meilleure musique ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 323,
    round_id: 4,
    name: "Qui est la personne la plus sûre de ce qu’elle est ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 324,
    round_id: 4,
    name: "Qui choisirais-tu comme témoin de mariage ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 325,
    round_id: 4,
    name: "Qui choisirais-tu comme parrain/marraine de ton enfant ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 326,
    round_id: 4,
    name: "Qui a les convictions les plus différentes des tiennes ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 327,
    round_id: 4,
    name: "D'après toi, qui fait le moins les choses à moitié ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 328,
    round_id: 4,
    name: "Qui a les valeurs les plus similaires aux tiennes ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  // {
  //   id: 329,
  //   round_id: 4,
  //   name: "avec qui n’aurais-tu pas pu être ami·e au collège ?",
  //   answer_1: null,
  //   answer_2: null,
  //   answer_3: null,
  //   answer_4: null,
  // },
  {
    id: 4441,
    round_id: 4,
    name: "D'après toi, qui est le plus susceptible de mettre ses enfants dans le privé ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 4442,
    round_id: 4,
    name: "Qui trouves-tu le plus souriant ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 4443,
    round_id: 4,
    name: "Avec qui monterais-tu un business ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 4444,
    round_id: 4,
    name: "En rentrant d’un long voyage, qui voudrais-tu voir en premier ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 4445,
    round_id: 4,
    name: "Qui verrais-tu le plus en super héros ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
  {
    id: 4446,
    round_id: 4,
    name: "Qui verrais-tu le plus en méchant machiavélique ?",
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
  },
];
